export const products = [
  {
    id: 1,
    name: "Producto 1",
    image: "/imgs/products/producto1.png",
    stock: "Disponible",
    price: "$22.222",
    prenda: "remera",
    talle: "M",
  },
  {
    id: 2,
    name: "Producto 2",
    image: "/imgs/products/producto2.png",
    stock: "Disponible",
    price: "$20.000",
    prenda: "buzo",
    talle: "L",
  },
  {
    id: 3,
    name: "Producto 3",
    image: "/imgs/products/producto3.png",
    stock: "Agotado",
    price: "$18.500",
    prenda: "remera",
    talle: "S",
  },
  {
    id: 4,
    name: "Producto 4",
    image: "/imgs/products/producto4.png",
    stock: "Disponible",
    price: "$25.000",
    prenda: "buzo",
    talle: "M",
  },
  {
    id: 5,
    name: "Producto 5",
    image: "/imgs/products/producto5.png",
    stock: "Últimas unidades",
    price: "$19.999",
    prenda: "remera",
    talle: "L",
  },
  {
    id: 6,
    name: "Producto 6",
    image: "/imgs/products/producto6.png",
    stock: "Disponible",
    price: "$21.500",
    prenda: "remera",
    talle: "S",
  },
];
